### ISSUE TITLE
测量的是实际面积吗

### ISSUE THREAD

**Issue by chenyuanpengcyp** [veraposeidon/PointCloudVolumeMeasure#1]

**Comment by veraposeidon** [comment]
是的，Kinect基本上是准的，可以标定测试一下。

**Comment by abbott1234** [comment]
@veraposeidon 點雲數據的單位怎麼轉換成cm或者mm的？

**Comment by veraposeidon** [comment]
@abbott1234 这个应该根据采集点云的设备来判断是否需要标定，比如我代码测试的时候用的Kinect V2，它采集得到的点云数据，数据的单位应该就是m。你可以尝试比较一下采集到的数值与实际的距离，看看是否需要标定。至于更深入的点云采集标定，就需要你自己去查查资料了。
