### ISSUE TITLE
Opencv链接器错误：Unresolved external symbol. cv::minAreaRect

### ISSUE THREAD

**Issue by lee2430** [veraposeidon/PointCloudVolumeMeasure#3]
Xiaohai 你好。
我按照win10配置文档配置完openni2后，安装了PCL1.8.1-all-in-one，用简单代码测试过openni2调用kinect和PCL的cloudviewer都没有问题。
之后编译运行这个项目发现缺少opencv，我先后下载了opencv的347，2413和411的官方build版本，都会有不同数量的unresolved external symbols错误。
2413版本13个，347版本7个，411版本一个，其中411版本剩下一个错误报在cv::minAreaRect函数上，另外两个版本我看基本也都是和Rect有关的函数。
我对c++版本的opencv比较陌生，想请问应该怎么解决这个问题，是需要在某些第三方支持下从源码编译opencv吗？谢谢。

**Comment by veraposeidon** [comment]
你好，抱歉之前没看到此条消息。
首先，OpenCV和PCL是两码事。PCL装好了那就是装好了，只需要解决OpenCV的问题。
关于OpenCV的话，我认为你应该是配置出问题了，像minAreaRect是OpenCV的基本函数，解决掉配置问题即可。
可以参考这篇文章（我随便找的https://blog.csdn.net/hosea1008/article/details/52712323。）或者你直接把我的opencv2413_debug_x64.props、opencv2413_release_x64.props里面的内容改成你自己安装的OpenCV2413的路径）。
然后，试着新建一个工程，显示一副图像，能显示就表示你的OpenCV能用了。（另外再推荐一下教程：https://blog.csdn.net/zhmxy555/article/category/1923021）。
至于你说的重新编译，不需要的。配置好就可以用了。
加油！

**Comment by lee2430** [comment]
@veraposeidon 多谢回复。确实是opencv链接器配置出的问题，当时新建opencv测试工程可以显示图像，但是这个项目build出来就是不好使，所以很懵~
后来发现是cmake的build直接在项目属性里指定了链接器的路径（我是cmake小白），而导致添加的props都不生效。所以在项目属性里直接改链接器位置就可以正常运行了。
