### ISSUE TITLE
请问这可以在ubuntu16.04上用吗

### ISSUE THREAD

**Issue by YuluGan** [veraposeidon/PointCloudVolumeMeasure#5]

**Comment by veraposeidon** [comment]
@YuluGan 可以啊，Ubuntu下也能装PCL和OpenCV库。

**Comment by YuluGan** [comment]
能麻烦告知一下怎么用嘛，我第一次接触，我看没有cmakelist，怎么运行呢？（运行哪个文件？这是整一个工作空间吗？）

**Comment by veraposeidon** [comment]
@YuluGan ，额，这份代码是windows + visual studio 下的工程，我是指main.cpp的源码流程可以在Linux下跑，但是具体的CmakeList.TXT得要你自己构建了。而且前期需要你安装OpenCV库和PCL库，可能要从源码编译安装。
建议你先找找教程实现这两个库的安装，以及运行代码测试是否安装成功。然后Cmakelist就很好写了啊。
